spring.application.name=BootProj72-SpbMSProj01

#Eureka server
server.port=8761

#Disable two properties inherited from parent project
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false