spring.application.name=BootProj99-U9-1-SpbMSProj12-CloudAPIGateway


#API Gateway port number
server.port=9191

#Register with eureka server
eureka.client.serviceUrl.default-zone=http://localhost:8761/eureka

#route and predicate configuration
spring.cloud.gateway.routes[0].id=ProviderBillingMS
spring.cloud.gateway.routes[0].uri=http://localhost:9091/
spring.cloud.gateway.routes[0].predicates[0]=Path=/billing-api/*


#route and predicate configuration
spring.cloud.gateway.routes[1].id=ConsumerCartMS-DiscoveryClient
spring.cloud.gateway.routes[1].uri=http://localhost:6061/
spring.cloud.gateway.routes[1].predicates[0]=Path=/cart-api/cart/*


