spring.application.name=BootProj86-SpbMSProj06-ConfigServer

#Config server port
server.port=8888

#Link with external config file
spring.cloud.config.server.git.uri=https://github.com/RaviKCoder/External-Config.git
