
#service id
spring.application.name=ProviderBillingMS


#instance id
spring.application.instance-id=${spring.application.name}:${server.port}:${random.value}

#MS port
server.port=9091


#connect to admin server
spring.boot.admin.client.url=http://localhost:9292



#register with eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#get more details from health actuator
management.endpoint.health.show-details=always

#Deactivate health actuator
#management.endpoint.health.access=none


#activate health,info actuators
#management.endpoints.web.exposure.include=health,info 

#activate health,info actuators
management.endpoints.web.exposure.include=*


#activate shoutdown actuators
management.endpoint.shutdown.access=unrestricted


#config properties
management.endpoint.configprops.show-values=always

#env values
management.endpoint.env.show-values=always

#logger level for com.ravi package
logging.level.com.ravi=debug


#get more details from info actuator
management.endpoint.info.access=unrestricted
management.info.env.enabled=true

#activate heapdump
management.endpoint.heapdump.access=unrestricted

#Actuator base path
#management.endpoints.web.base-path=/nitactuator


#Project information
info.add.name=OpenFx
info.app.size=100
info.app.addrs=hyd
info.app.lead=Ravi
